version: '3.8'
services:
  scope:
    image: weaveworks/scope:latest
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"

  # IL CUORE DATI
  redis:
    image: redis:7-alpine
    networks:
      - pwm-net

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=pwm_tactical_database
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - pwm-net

  frontend-dev:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8100:8100"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - pwm-net

  # AUTH & ELO
  auth-service:
    build: ./services/auth-elo
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_URL=postgres://postgres:secret@db:5432/pwm_tactical_database
    networks:
      - pwm-net

  # ENGINE SPOSTAMENTI
  engine-move:
    build: ./services/movement
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=MIA_CHIAVE_SEGRETA_2026
    volumes:
      - ./shared/assets:/app/assets:ro
    networks:
      - pwm-net

  # ENGINE COMBATTIMENTI
  engine-combat:
    build: ./services/combat
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - pwm-net

  # ENGINE RISORSE
  engine-res:
    build: ./services/resources
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - pwm-net

  # CHAT
  chat:
    build: ./services/chat
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - pwm-net

  # GATEWAY DI INGRESSO
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../frontend/www:/usr/share/nginx/html
      - ./shared/assets:/usr/share/nginx/html/assets:ro 
    depends_on:
      - auth-service
      - engine-move
      - engine-combat
      - engine-res
      - chat
    networks:
      - pwm-net

  # --- RIPRISTINA ASSETS ---
  ripristina:
    build:
      context: .
      dockerfile: ./services/ripristina/Dockerfile
    volumes:
      - ./shared/assets:/app/assets
    networks:
      - pwm-net

  # --- AMMINISTRATORE ---
  amministratore:
    build: ./services/amministratore
    ports:
      - "8080:8080" # Pannello admin (es. http://localhost:8080)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Necessario per controllare gli altri container
    depends_on:
      - ripristina
    networks:
      - pwm-net

  # --- STRUMENTI DI VISUALIZZAZIONE DATABASE ---
  pgadminer:
    image: adminer
    ports:
      - "8085:8080" # Porta non canonica esterna per visualizzare Postgres
    depends_on:
      - db
    networks:
      - pwm-net
      
  redis-ui:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8086:8081" # Porta non canonica esterna per visualizzare Redis
    depends_on:
      - redis
    networks:
      - pwm-net

networks:
  pwm-net:
    driver: bridge
