FROM node:18-alpine

WORKDIR /app

COPY gateway/package.json ./package.json
RUN npm install --omit=dev

COPY gateway/app-route.js ./app-route.js
COPY services/auth-elo ./services/auth-elo

EXPOSE 3001

CMD ["node", "app-route.js"]
