events {
  worker_connections 1024;
}

http {
  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

  upstream app_route {
    server app-route:3001;
  }
  upstream engine_move {
    server engine-move:3000;
  }

  server {
    listen 80;

    location /auth/ {
      proxy_pass http://app_route;
    }

    location /player/ {
      proxy_pass http://app_route;
    }

    location /home/ {
      proxy_pass http://app_route;
    }

    location /match {
      proxy_pass http://app_route;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }

    location /socket.io/ {
      proxy_pass http://engine_move;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }

    location / {
      root /usr/share/nginx/html;
      index index.html;
    }

    # Gestione asset condivisi (TIFF, CDB, Modelli)
    location /assets/ {
        alias /usr/share/nginx/html/assets/;
        add_header Access-Control-Allow-Origin *; # Permette al JS di leggere i file
    }
  }
}
